In [1]:
import numpy as np

In [4]:
#creat -from lists
arr=np.array([1,2,3,34])
print(arr,type(arr),arr.shape)

arr2=  np.array([1,2,3,4,5,"Roshan"])
print(arr2,type(arr2),arr2.dtype, arr2.shape)

[ 1  2  3 34] <class 'numpy.ndarray'> (4,)
['1' '2' '3' '4' '5' 'Roshan'] <class 'numpy.ndarray'> <U21 (6,)


In [6]:
# creating  2d array using 2 d list
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d, arr2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [24]:
#creating numpy array auto assigned 0 value
arr1 = np.zeros((2,3),dtype="int64")#prifilled with zero
print(arr1)
#prifilled with one 
arr2 = np.ones((2,3),dtype="int64")#prifilled with ones
print(arr2)
# prifilled with user given value
arr3=np.full((2,3),200)
print(arr3)

#creting a indentity matrix : identity matrices are those matrix in which digonal values are 1 and other values are always zero and num of rows= nums of column 
arr4=np.eye(3)
print(arr4)

#using arange function : used to create arrays within range

arr5=np.arange(0,11,2)# starting from 0 to 10 with the space of 2
print(arr5)


# creating array using linspace function :used to create a evenly spaced array
arr6=np.linspace(1,100,4)  # evenly spaced arrays
print(arr6)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[200 200 200]
 [200 200 200]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  2  4  6  8 10]
[  1.  34.  67. 100.]
