In [1]:
import numpy as np


In [5]:
# operations on array
arr=np.array([1,2,3,4,5,67])
arr=arr.reshape(3,2)

reshaped=arr.reshape(3,2)# reshaping the array

arr=arr.flatten() # flattening the array again into original shape


print(arr)

print(reshaped)

[ 1  2  3  4  5 67]
[[ 1  2]
 [ 3  4]
 [ 5 67]]


In [6]:
# indexing in array
# as simple as list indexing
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [7]:
#indexing at 2d array using column and row name
arr=np.array([[1,2,3],[1,2,3]])
print(arr[1,2])

3


In [9]:
#fancy indexing
arr=np.array([1,2,3,4,5])
idx=[0,1,3]
print(arr[idx])

#boolean indexing : based on particular condition filtering out specific values from array

print(arr[arr%2==0])

[1 2 4]
[2 4]


In [11]:
# slicing in numpy array's similar to python list but something is different in internal functionality which we will be covering down 
arr=np.array([1,2,3,4,5])
print(arr[1:4]) # includes beginning index and exclude's ending index

print(arr[1:]) # start from given index till last

print(arr[:4]) # starts from o to n-1


[2 3 4]
[2 3 4 5]
[1 2 3 4]


In [13]:
# concept of view and copy
# slicing in list:-  whenever we slice a list in python it creates a copy of list in memory 
# slicing in numpy array:- whenever we slice a array in python it does not create a copy like list we just see a view of original array 

# THIS IS ONE OF REASON WHY NUMPY ARRAY'S ARE FASTER THEN LISTS

#using concept on list of python 
nums=[1,2,3,4,5]
sub_list=nums[1:3]
sub_list[0]=200

print(sub_list)

print(nums) # no change in original list  showing the concept of copy in list

# applying concept on numpy array

arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]
sub_arr[0]=200
print(sub_arr)
print(arr) # there is change in original array showing the concept of view


[200, 3]
[1, 2, 3, 4, 5]
[200   3]
[  1 200   3   4   5]


In [ ]:
#we have copy function to make copy for arrarys 