In [1]:
import torch
import torch.nn as nn

In [2]:
# input
torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])


In [3]:
neuron = nn.Linear(in_features=3, out_features=1)

In [4]:
output = neuron(inputs)

In [5]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [6]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [7]:
#verify

neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)