In [7]:
import numpy as np
# multidimesional arrays are used in image generation  and to represent images in computer system mostly black white 
# colored images uses rgb values(red, green, blue)(0-255)
# these 2 d arrays called matrices in programming 


In [2]:
"""
1D ARRAy : 1 Axis(axis 0)
2D ARRAy : 2 Axis(axis 0-rows,  axis1- column)
3D ARRAy : 3 Axis(axis 0-depth/layers,   axis 1-rows,  axis2- column)"""

'\n1D ARRAy : 1 Axis(axis 0)\n2D ARRAy : 2 Axis(axis 0-rows,  axis1- column)\n3D ARRAy : 3 Axis(axis 0-depth/layers,   axis 1-rows,  axis2- column)'

In [15]:
# multi dimensional arrays
arr2d= np.array([[1,2,3],[1,2,3],[4,5,6]])
print(arr2d)
# sum of rows
print(np.sum(arr2d, axis= 1))
#sum of columns
print(np.sum(arr2d, axis= 0))

# slicing in axis wise
print(arr2d[0:3,1:2])

[[1 2 3]
 [1 2 3]
 [4 5 6]]
[ 6  6 15]
[ 6  9 12]
[[2]
 [2]
 [5]]


In [18]:
# 3d array

arr3d=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2x3x2
print(arr3d,arr3d.shape)
#aceesing the element of 3d arrays suppose we are accesing 4
print(arr3d[0,1,1])
print(arr3d[1,1,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
